### ISSUE TITLE
Severe conflict between MCV - Biomes O'Plenty and Embeddium.

### ISSUE THREAD

**Issue by Empmortakaten** [LieOnLion/MCV-BiomesOPlenty#6]
There's an issue with a MCV chest and Embeddium.  It spit out the attached crash report.  When the chest is placed it crashes everyone in the area.  Anyone that attempts to load into the area also crashes, requiring the mod to be removed, the chunk it is placed in to be reverted to a backup, or an out of game editing tool to be used to remove the block in question.

[crash-2024-07-28_23.00.02-client.txt](https://github.com/user-attachments/files/16406961/crash-2024-07-28_23.00.02-client.txt)

**Comment by LieOnLion** [comment]
It's not Embeddium. Update MCV-BOP to the beta version
