### ISSUE TITLE
Minecraft error after joining a created modded world

### ISSUE THREAD

**Issue by Allo1237217** [LieOnLion/MCV-BiomesOPlenty#7]
This is the error massage:

The game crashed whilst rendering block entity
Error: java.lang.NoClassDefFoundError: io/github/lieonlion/mcv/client/MoreChestRenderer

**Comment by LieOnLion** [comment]
Please update MCV Biomes O Plenty addon to the beta version. 
If you are using the MCV Biome Makeover addon, unfortunately its not fixed yet

**Comment by Allo1237217** [comment]
thanks so much

> Please update MCV Biomes O Plenty addon to the beta version. If you are using the MCV Biome Makeover addon, unfortunately its not fixed yet

thanks so much

**Comment by Allo1237217** [comment]
it still does the same thing
